from . import database
from flask_login import UserMixin
from sqlalchemy.sql import func

class User(database.Model, UserMixin):

    id            = database.Column(database.Integer, primary_key=True)
    email         = database.Column(database.String(100), unique=True)
    username      = database.Column(database.String(100), unique=True)
    nameSurname   = database.Column(database.String(100))
    password      = database.Column(database.String(100))
    isActive      = database.Column(database.Boolean)
    isAdmin       = database.Column(database.Boolean)
    isEditor      = database.Column(database.Boolean)
    isTranscriber = database.Column(database.Boolean)
    samples                       = database.relationship('Sample')
    totalRecoringsLengtMilisec    = database.Column(database.Integer)
    approvedRecoringsLengtMilisec = database.Column(database.Integer)
    prizeSelect = database.Column(database.String(200))
    prizeSend   = database.Column(database.Boolean)

class Sample(database.Model):

    id         = database.Column(database.Integer, primary_key=True)
    userID     = database.Column(database.Integer, database.ForeignKey('user.id'))
    uploadDate = database.Column(database.DateTime(timezone=True), default=func.now())
    metaUploadNoSpeakers  = database.Column(database.Integer)
    metaUploadSource      = database.Column(database.Integer)
    metaUploadLocation    = database.Column(database.String(200)) 
    metaUploadRooms       = database.Column(database.String(200))
    metaUploadDate        = database.Column(database.String(20))
    metaUploadChannel     = database.Column(database.Integer)
    metaUploadSpeechType  = database.Column(database.Integer)
    metaUploadTool        = database.Column(database.String(200))
    metaUploadDescription = database.Column(database.String(1000))
    metaUploadKeyWords    = database.Column(database.String(200))
    metaTechFileSizeBytes = database.Column(database.Integer)
    metaTechFileFormat    = database.Column(database.String(10))
    metaTechLengthMilisec = database.Column(database.Integer)
    metaTechFilenameWave  = database.Column(database.String(500))
    metaTechFilenameFrmA  = database.Column(database.String(500))
    metaTechFilenameFrmB  = database.Column(database.String(500))
    metaTechFilenameFrmC  = database.Column(database.String(500))
    metaTechFilenameMeta  = database.Column(database.String(500))
    metaEditingTextID        = database.Column(database.String(500))
    metaEditingSourceID      = database.Column(database.String(500))
    metaEditingRecodingID    = database.Column(database.String(500))
    metaEditingSubcorpus     = database.Column(database.String(100))
    metaEditingDescription   = database.Column(database.String(1000))
    metaEditingDate          = database.Column(database.String(20))
    metaEditingSource        = database.Column(database.String(100))
    metaEditingLocation      = database.Column(database.String(100)) 
    metaEditingSpeechDomain  = database.Column(database.String(100))
    metaEditingSpeechType    = database.Column(database.String(100))
    metaEditingChannel       = database.Column(database.String(100))
    metaEditingKeywords      = database.Column(database.String(200))
    metaEditingDevice        = database.Column(database.String(200))
    metaEditingRooms         = database.Column(database.String(200))
    metaEditingQuality       = database.Column(database.String(20))
    metaEditingURL           = database.Column(database.String(200))
    metaEditingLengthAprv    = database.Column(database.Integer)
    metaEditingChecked       = database.Column(database.Boolean)
    metaEditingApprovedQ     = database.Column(database.Boolean)
    metaEditingApprovedForT  = database.Column(database.Boolean)
    metaEditingCommentForT   = database.Column(database.String(500))
    metaEditingStartedT      = database.Column(database.Boolean)
    metaEditingApprovedTRS   = database.Column(database.Boolean)
    metaEditingEditorComment = database.Column(database.String(500))
    metaEditingNameOfEditor  = database.Column(database.String(100))
    metaEditingLastEditTime  = database.Column(database.String(25))

class Speaker(database.Model):

    id             = database.Column(database.Integer, primary_key=True)
    recordingID    = database.Column(database.Integer, database.ForeignKey('sample.id'))
    recordingOrder = database.Column(database.Integer)
    bindingID      = database.Column(database.Integer)
    metaUploadName       = database.Column(database.String(100))
    metaUploadGender     = database.Column(database.String(50))
    metaUploadAge        = database.Column(database.String(50))
    metaUploadEducation  = database.Column(database.String(50))
    metaUploadBilingual  = database.Column(database.String(10))
    metaUploadLanguageA  = database.Column(database.String(50))
    metaUploadLanguageB  = database.Column(database.String(50))
    metaUploadLocationA  = database.Column(database.String(100))
    metaUploadLocationB  = database.Column(database.String(100))
    metaUploadLocationC  = database.Column(database.String(200))
    metaEditingTextID       = database.Column(database.String(100))
    metaEditingSourceID     = database.Column(database.String(100))
    metaEditingRecordingID  = database.Column(database.String(100))
    metaEditingSubcorpus    = database.Column(database.String(100))
    metaEditingPRSID        = database.Column(database.String(100))
    metaEditingGender       = database.Column(database.String(50))
    metaEditingAge          = database.Column(database.String(50))
    metaEditingLanguageA    = database.Column(database.String(50))
    metaEditingDialectType  = database.Column(database.String(50))
    metaEditingDialectGRP   = database.Column(database.String(50))
    metaEditingDialect      = database.Column(database.String(50))
    metaEditingEducation    = database.Column(database.String(50))
    metaEditingLocationA    = database.Column(database.String(100))
    metaEditingLocARegion   = database.Column(database.String(100))
    metaEditingLocACountry  = database.Column(database.String(100))
    metaEditingLocationB    = database.Column(database.String(100))
    metaEditingLocBRegion   = database.Column(database.String(100))
    metaEditingLocBCountry  = database.Column(database.String(100))
    metaEditingLocationC    = database.Column(database.String(200))
    metaEditingLocCRegion   = database.Column(database.String(200))
    metaEditingLocCCountry  = database.Column(database.String(200))
    metaEditingBilingual    = database.Column(database.String(10))
    metaEditingLanguageB    = database.Column(database.String(50))
    metaEditingNameOfEditor = database.Column(database.String(100))
    metaEditingLastEditTime  = database.Column(database.String(25))
    
class Transcript(database.Model):

    id           = database.Column(database.Integer, primary_key=True)
    recordingID  = database.Column(database.Integer)
    trsType      = database.Column(database.Integer)
    version      = database.Column(database.Integer)
    fileName     = database.Column(database.String(500))
    transcriber  = database.Column(database.String(205))
    approved     = database.Column(database.Boolean) 
    approvedBy   = database.Column(database.String(205))
    approvedDate = database.Column(database.String(25))
